<?php

/**
 * Basetest
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class Basetest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('test');
    }

    public function setUp()
    {
        $file0 = new file(array(
             'pathname' => 
             array(
              'name' => 'path_name',
             ),
             ));
        $this->actAs($file0);
    }
}