<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasesfFilebaseFile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_filebase_files');
        $this->hasColumn('pathname', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('hash', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));
        $this->hasColumn('comment', 'string', null, array('type' => 'string'));
        $this->hasColumn('sf_filebase_directory_id', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('type', 'string', 255, array('type' => 'string', 'length' => 255));


        $this->index('u1', array('type' => 'unique', 'fields' => array(0 => 'pathname')));
        $this->index('u2', array('type' => 'unique', 'fields' => array(0 => 'hash')));
        $this->setSubClasses(array('sfFilebaseDirectory' => array('type' => '1')));
    }

    public function setUp()
    {
        $this->hasOne('sfFilebaseDirectory', array('local' => 'sf_filebase_directory_id',
                                                   'foreign' => 'id',
                                                   'onDelete' => 'cascade',
                                                   'onUpdate' => 'cascade'));

        $this->hasMany('sfFilebaseTag', array('local' => 'id',
                                              'foreign' => 'sf_filebase_files_id'));
    }
}