<?php

/**
 * BasesfFilebaseDirectory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $descendants
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class BasesfFilebaseDirectory extends sfAbstractFile
{
    public function setUp()
    {
        parent::setUp();
    $this->hasMany('sfAbstractFile as descendants', array(
             'local' => 'id',
             'foreign' => 'root_id'));
    }
}