<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasesfFilebaseDirectory extends sfFilebaseFile
{
    public function setUp()
    {
        parent::setUp();
    $this->hasMany('sfFilebaseFile', array('local' => 'id',
                                               'foreign' => 'sf_filebase_directory_id'));
    }
}