<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasesfFilebaseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_filebase_tags');
        $this->hasColumn('sf_filebase_files_id', 'integer', null, array('type' => 'integer', 'notnull' => true));
        $this->hasColumn('tag', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));


        $this->index('i1', array('fields' => array(0 => 'tag')));
    }

    public function setUp()
    {
        $this->hasOne('sfFilebaseFile', array('local' => 'sf_filebase_files_id',
                                              'foreign' => 'id',
                                              'onDelete' => 'cascade',
                                              'onUpdate' => 'cascade'));
    }
}