<?php

/**
 * BasesfFilebaseTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sf_abstract_files_id
 * @property string $tag
 * @property sfAbstractFile $File
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
abstract class BasesfFilebaseTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_filebase_tags');
        $this->hasColumn('sf_abstract_files_id', 'integer', null, array('type' => 'integer'));
        $this->hasColumn('tag', 'string', 255, array('type' => 'string', 'notnull' => true, 'length' => '255'));


        $this->index('i1', array('fields' => array(0 => 'tag')));
    }

    public function setUp()
    {
        $this->hasOne('sfAbstractFile as File', array('local' => 'sf_abstract_files_id',
                                                      'foreign' => 'id',
                                                      'onDelete' => 'cascade',
                                                      'onUpdate' => 'cascade'));
    }
}