<?php

/**
 * Basetesterer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
abstract class Basetesterer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tester');
    }

    public function setUp()
    {
        $file0 = new Doctrine_Template_File(array(
             'name' => 'path_name',
             'filebaseDirectory' => '/home/joshi/www/test/plugins/sfFilebasePlugin/config/doctrine/../../test/assets',
             ));
        $this->actAs($file0);
    }
}