<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfAbstractFile extends BasesfAbstractFile
{
  /**
   * Returns the tags as a string representation.
   * @param string $separator
   * @return string $tag_string
   */
  public function getTagsAsString($separator = ', ')
  {
    $tags = array();
    foreach($this->getTags() AS $tag)
    {
      $tags[] = $tag->getTag();
    }
    return implode($separator, $tags);
  }

  /**
   * Sets the tags for this file.
   *
   * @param array $tags
   */
  public function setTags(array $tags)
  {
    Doctrine_Query::create()->
      from('sfFilebaseTag t')->
      delete()->
      where('t.sf_abstract_files_id='.$this->getId())->
      execute();

    foreach ($tags AS $tag)
    {
      $new_tag = new sfFilebaseTag();
      $new_tag->setTag($tag);
      $new_tag->setFile($this);
      $this->tags[] = $new_tag;
    }
  }

  public function __toString()
  {
    return (string)$this->getPathname();
  }

  /**
   *
   * @return string link to the parent directories edit page
   */
  public function getParentDirectoryLink()
  {
    $p = $this->getsfFilebaseDirectoriesId();
    return empty($p) ? '' :
            link_to($this->getParentDirectory()->getPathname(), 'sf_filebase_directory_edit', $this->getParentDirectory());
  }
}