<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfFilebaseFile extends BasesfFilebaseFile
{
  public function delete(Doctrine_Connection $conn = null)
  {
    $conn === null && $conn = Doctrine::getConnectionByTableName($this->getTable()->getTableName());
    
    try 
    {
      $conn->beginTransaction();
      $f = sfFilebasePlugin::getInstance();
      $f[$this->getPathname()]->delete();
      parent::delete($conn);
      $conn->commit();
    }
    catch (Exception $e)
    {
      $conn->rollback();
      throw $e;
    }
  }

  public function save(Doctrine_Connection $conn = null)
  {
    $conn === null && $conn = Doctrine::getConnectionByTableName($this->getTable()->getTableName());
    try
    {
      $conn->beginTransaction();
      if(!$this->isNew())
      {
        $fields = $this->getModified();
        if(isset($fields['pathname']))
        {
          $o = Doctrine_Query::create()->select('*')->from(get_class($this) . ' f')->
                where('f.id='.$this->getId())->execute()->get(0);
          
          $old_pathname = $o->getPathname();
          $f = sfFilebasePlugin::getInstance();
          $new_name = $f->getFilebaseFile($fields['pathname'])->getFilename();
          $f[$old_pathname]->rename($new_name);
          $this->setPathname($fields['pathname']);
        }
      }
      parent::save($conn);
      $conn->commit();
    }
    catch (Exception $e)
    {
      $conn->rollback();
      throw $e;
    }
  }
}