<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfAbstractFile extends BasesfAbstractFile
{
  protected $original_filename            = false;
  protected $original_path                = false;
  protected $original_parent_directory_id = false;

  public function preSave($event)
  {
    // Ensure the constraint between directory flag and
    // path.
    if($this->original_parent_directory_id !== false)
    {
      $path = $this->getParentDirectory()->getPathname() ?
        $this->getParentDirectory()->getPathname() :
        sfFilebasePlugin::getInstance()->getPathname();
      $this->setPath($path);
      $this->original_parent_directory_id = false;
    }
  }

  public function set($fieldName, $value, $load = true)
  {
    if($this->$fieldName !== $value)
    {
      switch($fieldName)
      {
        case 'filename';
          if($this->original_filename === false)
          {
            $this->original_filename = $this->getFilename();
          }
          break;
        case 'path':
          if($this->original_path === false)
          {
            $this->original_path = $this->getPath();
          }
          break;
        case 'sf_filebase_directories_id':
          if($this->original_parent_directory_id === false)
          {
            $this->original_parent_directory_id = $this->sf_filebase_directories_id;
          }
          break;
      }
    }
    return parent::set($fieldName, $value, $load);
  }
  
  /**
   * Returns the tags as a string representation.
   * @param string $separator
   * @return string $tag_string
   */
  public function getTagsAsString($separator = ', ')
  {
    $tags = array();
    foreach($this->getTags() AS $tag)
    {
      $tags[] = $tag->getTag();
    }
    return implode($separator, $tags);
  }

  /**
   * Sets the tags for this file.
   *
   * @param array $tags
   */
  public function setTags(array $tags)
  {
    Doctrine_Query::create()->
      from('sfFilebaseTag t')->
      delete()->
      where('t.sf_abstract_files_id='.$this->getId())->
      execute();

    foreach ($tags AS $tag)
    {
      $new_tag = new sfFilebaseTag();
      $new_tag->setTag($tag);
      $new_tag->setFile($this);
      $this->tags[] = $new_tag;
    }
  }

  public function __toString()
  {
    return (string)$this->getFilename();
  }

  /**
   *
   * @return string link to the parent directories edit page
   */
  public function getParentDirectoryLink()
  {
    $p = $this->getsfFilebaseDirectoriesId();
    return empty($p) ? '' :
            link_to($this->getParentDirectory()->getPathname(), 'sf_filebase_directory_edit', $this->getParentDirectory());
  }

  public function getPathname()
  {
   if(!$this->getPath() || !$this->getFilename())
   {
     return null;
   }
   return   $this->getPath() . '/' . $this->getFilename() ;
  }
}