<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/05/12 15:36:05
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
