<?php

/**
 * Base class that represents a row from the 'sf_filebase_files' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat May 16 21:42:36 2009
 *
 * @package    plugins.sfFilebasePlugin.lib.model.om
 */
abstract class BasesfFilebaseFile extends BaseObject  implements Persistent {


  const PEER = 'sfFilebaseFilePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        sfFilebaseFilePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the pathname field.
	 * @var        string
	 */
	protected $pathname;

	/**
	 * The value for the hash field.
	 * @var        string
	 */
	protected $hash;

	/**
	 * The value for the comment field.
	 * @var        string
	 */
	protected $comment;

	/**
	 * The value for the sf_filebase_directories_id field.
	 * @var        int
	 */
	protected $sf_filebase_directories_id;

	/**
	 * @var        sfFilebaseDirectory
	 */
	protected $asfFilebaseDirectory;

	/**
	 * @var        array sfFilebaseDirectory[] Collection to store aggregation of sfFilebaseDirectory objects.
	 */
	protected $collsfFilebaseDirectorys;

	/**
	 * @var        Criteria The criteria used to select the current contents of collsfFilebaseDirectorys.
	 */
	private $lastsfFilebaseDirectoryCriteria = null;

	/**
	 * @var        array sfFilebaseTag[] Collection to store aggregation of sfFilebaseTag objects.
	 */
	protected $collsfFilebaseTags;

	/**
	 * @var        Criteria The criteria used to select the current contents of collsfFilebaseTags.
	 */
	private $lastsfFilebaseTagCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BasesfFilebaseFile object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [pathname] column value.
	 * 
	 * @return     string
	 */
	public function getPathname()
	{
		return $this->pathname;
	}

	/**
	 * Get the [hash] column value.
	 * 
	 * @return     string
	 */
	public function getHash()
	{
		return $this->hash;
	}

	/**
	 * Get the [comment] column value.
	 * 
	 * @return     string
	 */
	public function getComment()
	{
		return $this->comment;
	}

	/**
	 * Get the [sf_filebase_directories_id] column value.
	 * 
	 * @return     int
	 */
	public function getSfFilebaseDirectoriesId()
	{
		return $this->sf_filebase_directories_id;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     sfFilebaseFile The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = sfFilebaseFilePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [pathname] column.
	 * 
	 * @param      string $v new value
	 * @return     sfFilebaseFile The current object (for fluent API support)
	 */
	public function setPathname($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pathname !== $v) {
			$this->pathname = $v;
			$this->modifiedColumns[] = sfFilebaseFilePeer::PATHNAME;
		}

		return $this;
	} // setPathname()

	/**
	 * Set the value of [hash] column.
	 * 
	 * @param      string $v new value
	 * @return     sfFilebaseFile The current object (for fluent API support)
	 */
	public function setHash($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->hash !== $v) {
			$this->hash = $v;
			$this->modifiedColumns[] = sfFilebaseFilePeer::HASH;
		}

		return $this;
	} // setHash()

	/**
	 * Set the value of [comment] column.
	 * 
	 * @param      string $v new value
	 * @return     sfFilebaseFile The current object (for fluent API support)
	 */
	public function setComment($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->comment !== $v) {
			$this->comment = $v;
			$this->modifiedColumns[] = sfFilebaseFilePeer::COMMENT;
		}

		return $this;
	} // setComment()

	/**
	 * Set the value of [sf_filebase_directories_id] column.
	 * 
	 * @param      int $v new value
	 * @return     sfFilebaseFile The current object (for fluent API support)
	 */
	public function setSfFilebaseDirectoriesId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->sf_filebase_directories_id !== $v) {
			$this->sf_filebase_directories_id = $v;
			$this->modifiedColumns[] = sfFilebaseFilePeer::SF_FILEBASE_DIRECTORIES_ID;
		}

		if ($this->asfFilebaseDirectory !== null && $this->asfFilebaseDirectory->getId() !== $v) {
			$this->asfFilebaseDirectory = null;
		}

		return $this;
	} // setSfFilebaseDirectoriesId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->pathname = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->hash = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->comment = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->sf_filebase_directories_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 5; // 5 = sfFilebaseFilePeer::NUM_COLUMNS - sfFilebaseFilePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating sfFilebaseFile object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->asfFilebaseDirectory !== null && $this->sf_filebase_directories_id !== $this->asfFilebaseDirectory->getId()) {
			$this->asfFilebaseDirectory = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfFilebaseFilePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = sfFilebaseFilePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->asfFilebaseDirectory = null;
			$this->collsfFilebaseDirectorys = null;
			$this->lastsfFilebaseDirectoryCriteria = null;

			$this->collsfFilebaseTags = null;
			$this->lastsfFilebaseTagCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasesfFilebaseFile:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfFilebaseFilePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			sfFilebaseFilePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BasesfFilebaseFile:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BasesfFilebaseFile:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(sfFilebaseFilePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BasesfFilebaseFile:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			sfFilebaseFilePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfFilebaseDirectory !== null) {
				if ($this->asfFilebaseDirectory->isModified() || $this->asfFilebaseDirectory->isNew()) {
					$affectedRows += $this->asfFilebaseDirectory->save($con);
				}
				$this->setsfFilebaseDirectory($this->asfFilebaseDirectory);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = sfFilebaseFilePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = sfFilebaseFilePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += sfFilebaseFilePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collsfFilebaseDirectorys !== null) {
				foreach ($this->collsfFilebaseDirectorys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collsfFilebaseTags !== null) {
				foreach ($this->collsfFilebaseTags as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfFilebaseDirectory !== null) {
				if (!$this->asfFilebaseDirectory->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfFilebaseDirectory->getValidationFailures());
				}
			}


			if (($retval = sfFilebaseFilePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collsfFilebaseDirectorys !== null) {
					foreach ($this->collsfFilebaseDirectorys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collsfFilebaseTags !== null) {
					foreach ($this->collsfFilebaseTags as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = sfFilebaseFilePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getPathname();
				break;
			case 2:
				return $this->getHash();
				break;
			case 3:
				return $this->getComment();
				break;
			case 4:
				return $this->getSfFilebaseDirectoriesId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = sfFilebaseFilePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getPathname(),
			$keys[2] => $this->getHash(),
			$keys[3] => $this->getComment(),
			$keys[4] => $this->getSfFilebaseDirectoriesId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = sfFilebaseFilePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setPathname($value);
				break;
			case 2:
				$this->setHash($value);
				break;
			case 3:
				$this->setComment($value);
				break;
			case 4:
				$this->setSfFilebaseDirectoriesId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = sfFilebaseFilePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPathname($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setHash($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setComment($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setSfFilebaseDirectoriesId($arr[$keys[4]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(sfFilebaseFilePeer::DATABASE_NAME);

		if ($this->isColumnModified(sfFilebaseFilePeer::ID)) $criteria->add(sfFilebaseFilePeer::ID, $this->id);
		if ($this->isColumnModified(sfFilebaseFilePeer::PATHNAME)) $criteria->add(sfFilebaseFilePeer::PATHNAME, $this->pathname);
		if ($this->isColumnModified(sfFilebaseFilePeer::HASH)) $criteria->add(sfFilebaseFilePeer::HASH, $this->hash);
		if ($this->isColumnModified(sfFilebaseFilePeer::COMMENT)) $criteria->add(sfFilebaseFilePeer::COMMENT, $this->comment);
		if ($this->isColumnModified(sfFilebaseFilePeer::SF_FILEBASE_DIRECTORIES_ID)) $criteria->add(sfFilebaseFilePeer::SF_FILEBASE_DIRECTORIES_ID, $this->sf_filebase_directories_id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(sfFilebaseFilePeer::DATABASE_NAME);

		$criteria->add(sfFilebaseFilePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of sfFilebaseFile (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setPathname($this->pathname);

		$copyObj->setHash($this->hash);

		$copyObj->setComment($this->comment);

		$copyObj->setSfFilebaseDirectoriesId($this->sf_filebase_directories_id);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getsfFilebaseDirectorys() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addsfFilebaseDirectory($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getsfFilebaseTags() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addsfFilebaseTag($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     sfFilebaseFile Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     sfFilebaseFilePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new sfFilebaseFilePeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a sfFilebaseDirectory object.
	 *
	 * @param      sfFilebaseDirectory $v
	 * @return     sfFilebaseFile The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfFilebaseDirectory(sfFilebaseDirectory $v = null)
	{
		if ($v === null) {
			$this->setSfFilebaseDirectoriesId(NULL);
		} else {
			$this->setSfFilebaseDirectoriesId($v->getId());
		}

		$this->asfFilebaseDirectory = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfFilebaseDirectory object, it will not be re-added.
		if ($v !== null) {
			$v->addsfFilebaseFile($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfFilebaseDirectory object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfFilebaseDirectory The associated sfFilebaseDirectory object.
	 * @throws     PropelException
	 */
	public function getsfFilebaseDirectory(PropelPDO $con = null)
	{
		if ($this->asfFilebaseDirectory === null && ($this->sf_filebase_directories_id !== null)) {
			$c = new Criteria(sfFilebaseDirectoryPeer::DATABASE_NAME);
			$c->add(sfFilebaseDirectoryPeer::ID, $this->sf_filebase_directories_id);
			$this->asfFilebaseDirectory = sfFilebaseDirectoryPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfFilebaseDirectory->addsfFilebaseFiles($this);
			 */
		}
		return $this->asfFilebaseDirectory;
	}

	/**
	 * Clears out the collsfFilebaseDirectorys collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addsfFilebaseDirectorys()
	 */
	public function clearsfFilebaseDirectorys()
	{
		$this->collsfFilebaseDirectorys = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collsfFilebaseDirectorys collection (array).
	 *
	 * By default this just sets the collsfFilebaseDirectorys collection to an empty array (like clearcollsfFilebaseDirectorys());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initsfFilebaseDirectorys()
	{
		$this->collsfFilebaseDirectorys = array();
	}

	/**
	 * Gets an array of sfFilebaseDirectory objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this sfFilebaseFile has previously been saved, it will retrieve
	 * related sfFilebaseDirectorys from storage. If this sfFilebaseFile is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array sfFilebaseDirectory[]
	 * @throws     PropelException
	 */
	public function getsfFilebaseDirectorys($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfFilebaseFilePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collsfFilebaseDirectorys === null) {
			if ($this->isNew()) {
			   $this->collsfFilebaseDirectorys = array();
			} else {

				$criteria->add(sfFilebaseDirectoryPeer::SF_FILEBASE_FILES_ID, $this->id);

				sfFilebaseDirectoryPeer::addSelectColumns($criteria);
				$this->collsfFilebaseDirectorys = sfFilebaseDirectoryPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(sfFilebaseDirectoryPeer::SF_FILEBASE_FILES_ID, $this->id);

				sfFilebaseDirectoryPeer::addSelectColumns($criteria);
				if (!isset($this->lastsfFilebaseDirectoryCriteria) || !$this->lastsfFilebaseDirectoryCriteria->equals($criteria)) {
					$this->collsfFilebaseDirectorys = sfFilebaseDirectoryPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastsfFilebaseDirectoryCriteria = $criteria;
		return $this->collsfFilebaseDirectorys;
	}

	/**
	 * Returns the number of related sfFilebaseDirectory objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related sfFilebaseDirectory objects.
	 * @throws     PropelException
	 */
	public function countsfFilebaseDirectorys(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfFilebaseFilePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collsfFilebaseDirectorys === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(sfFilebaseDirectoryPeer::SF_FILEBASE_FILES_ID, $this->id);

				$count = sfFilebaseDirectoryPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(sfFilebaseDirectoryPeer::SF_FILEBASE_FILES_ID, $this->id);

				if (!isset($this->lastsfFilebaseDirectoryCriteria) || !$this->lastsfFilebaseDirectoryCriteria->equals($criteria)) {
					$count = sfFilebaseDirectoryPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collsfFilebaseDirectorys);
				}
			} else {
				$count = count($this->collsfFilebaseDirectorys);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a sfFilebaseDirectory object to this object
	 * through the sfFilebaseDirectory foreign key attribute.
	 *
	 * @param      sfFilebaseDirectory $l sfFilebaseDirectory
	 * @return     void
	 * @throws     PropelException
	 */
	public function addsfFilebaseDirectory(sfFilebaseDirectory $l)
	{
		if ($this->collsfFilebaseDirectorys === null) {
			$this->initsfFilebaseDirectorys();
		}
		if (!in_array($l, $this->collsfFilebaseDirectorys, true)) { // only add it if the **same** object is not already associated
			array_push($this->collsfFilebaseDirectorys, $l);
			$l->setsfFilebaseFile($this);
		}
	}

	/**
	 * Clears out the collsfFilebaseTags collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addsfFilebaseTags()
	 */
	public function clearsfFilebaseTags()
	{
		$this->collsfFilebaseTags = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collsfFilebaseTags collection (array).
	 *
	 * By default this just sets the collsfFilebaseTags collection to an empty array (like clearcollsfFilebaseTags());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initsfFilebaseTags()
	{
		$this->collsfFilebaseTags = array();
	}

	/**
	 * Gets an array of sfFilebaseTag objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this sfFilebaseFile has previously been saved, it will retrieve
	 * related sfFilebaseTags from storage. If this sfFilebaseFile is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array sfFilebaseTag[]
	 * @throws     PropelException
	 */
	public function getsfFilebaseTags($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfFilebaseFilePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collsfFilebaseTags === null) {
			if ($this->isNew()) {
			   $this->collsfFilebaseTags = array();
			} else {

				$criteria->add(sfFilebaseTagPeer::SF_FILEBASE_FILE_ID, $this->id);

				sfFilebaseTagPeer::addSelectColumns($criteria);
				$this->collsfFilebaseTags = sfFilebaseTagPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(sfFilebaseTagPeer::SF_FILEBASE_FILE_ID, $this->id);

				sfFilebaseTagPeer::addSelectColumns($criteria);
				if (!isset($this->lastsfFilebaseTagCriteria) || !$this->lastsfFilebaseTagCriteria->equals($criteria)) {
					$this->collsfFilebaseTags = sfFilebaseTagPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastsfFilebaseTagCriteria = $criteria;
		return $this->collsfFilebaseTags;
	}

	/**
	 * Returns the number of related sfFilebaseTag objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related sfFilebaseTag objects.
	 * @throws     PropelException
	 */
	public function countsfFilebaseTags(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(sfFilebaseFilePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collsfFilebaseTags === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(sfFilebaseTagPeer::SF_FILEBASE_FILE_ID, $this->id);

				$count = sfFilebaseTagPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(sfFilebaseTagPeer::SF_FILEBASE_FILE_ID, $this->id);

				if (!isset($this->lastsfFilebaseTagCriteria) || !$this->lastsfFilebaseTagCriteria->equals($criteria)) {
					$count = sfFilebaseTagPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collsfFilebaseTags);
				}
			} else {
				$count = count($this->collsfFilebaseTags);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a sfFilebaseTag object to this object
	 * through the sfFilebaseTag foreign key attribute.
	 *
	 * @param      sfFilebaseTag $l sfFilebaseTag
	 * @return     void
	 * @throws     PropelException
	 */
	public function addsfFilebaseTag(sfFilebaseTag $l)
	{
		if ($this->collsfFilebaseTags === null) {
			$this->initsfFilebaseTags();
		}
		if (!in_array($l, $this->collsfFilebaseTags, true)) { // only add it if the **same** object is not already associated
			array_push($this->collsfFilebaseTags, $l);
			$l->setsfFilebaseFile($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collsfFilebaseDirectorys) {
				foreach ((array) $this->collsfFilebaseDirectorys as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collsfFilebaseTags) {
				foreach ((array) $this->collsfFilebaseTags as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collsfFilebaseDirectorys = null;
		$this->collsfFilebaseTags = null;
			$this->asfFilebaseDirectory = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BasesfFilebaseFile:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BasesfFilebaseFile::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BasesfFilebaseFile
