<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2009/05/11 21:39:06
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
